/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List upcoming bookings (owner/admin).
         *
         *     Returns `200` with the owner's bookings ordered by start time. The
         *     optional `from` query restricts results to bookings starting at or after
         *     the given instant (defaults to "now").
         */
        get: operations["Bookings_list"];
        put?: never;
        /**
         * @description Create a booking for a slot (public).
         *
         *     The server derives `end` from the event type's duration and re-validates
         *     availability at write time. Returns `201` with the created `Booking`;
         *     `400` when `start` is off-grid, in the past, or out of the 14-day window
         *     (or the payload is otherwise invalid); `404` when the `eventTypeId` is
         *     unknown; `409` when the requested time overlaps an existing booking
         *     (global one-call-at-a-time rule).
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all event types (public).
         *
         *     Returns `200` with every event type the owner has defined.
         */
        get: operations["EventTypes_list"];
        put?: never;
        /**
         * @description Create a new event type (owner/admin).
         *
         *     Returns `201` with the created `EventType`, or `400` when the payload
         *     fails validation (e.g. blank title, non-positive duration).
         */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List available slots for an event type (public).
         *
         *     Slots are generated server-side on the 30-minute grid within business
         *     hours (09:00–17:00) such that `start + durationMinutes <= 17:00`, over
         *     the rolling 14-day window, excluding times that overlap existing
         *     bookings. The optional `date` query narrows results to a single day.
         *
         *     Returns `200` with the available slots, or `404` when the event type
         *     does not exist.
         */
        get: operations["EventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A confirmed reservation of a `Slot` by a `Guest`. */
        Booking: {
            /** @description Server-assigned unique identifier. */
            readonly id: string;
            /** @description The `EventType` this booking is for. */
            eventTypeId: string;
            /** @description The person who booked the call. */
            guest: components["schemas"]["Guest"];
            /**
             * Format: date-time
             * @description Inclusive start of the booked call (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Exclusive end of the booked call (UTC).
             */
            end: string;
            /** @description Optional note from the guest. */
            notes?: string;
            /**
             * Format: date-time
             * @description Server-assigned creation timestamp.
             */
            readonly createdAt: string;
        };
        /** @description Payload for creating a `Booking`. Read-only fields are omitted. */
        BookingCreate: {
            /** @description The `EventType` this booking is for. */
            eventTypeId: string;
            /** @description The person who booked the call. */
            guest: components["schemas"]["Guest"];
            /**
             * Format: date-time
             * @description Inclusive start of the requested call (UTC); must align to the slot grid.
             */
            start: string;
            /** @description Optional note from the guest. */
            notes?: string;
        };
        /**
         * @description A bookable type of call/meeting defined by the single owner
         *     (e.g. "30 minute intro call").
         */
        EventType: {
            /** @description Server-assigned unique identifier. */
            readonly id: string;
            /** @description Human-readable title shown to guests. */
            title: string;
            /**
             * Format: int32
             * @description Length of the call in minutes; drives slot generation.
             */
            durationMinutes: number;
            /** @description Optional description shown to guests. */
            description?: string;
        };
        /** @description Payload for creating an `EventType`. Read-only fields are omitted. */
        EventTypeCreate: {
            /** @description Human-readable title shown to guests. */
            title: string;
            /**
             * Format: int32
             * @description Length of the call in minutes; drives slot generation.
             */
            durationMinutes: number;
            /** @description Optional description shown to guests. */
            description?: string;
        };
        /** @description The person booking a call. */
        Guest: {
            /** @description Guest's full name. */
            name: string;
            /**
             * Format: email
             * @description Guest's email address; used to confirm the booking.
             */
            email: string;
        };
        /** @description Returned when a referenced resource (e.g. an `EventType`) does not exist. */
        NotFoundError: {
            /**
             * @description Discriminating error code.
             * @enum {string}
             */
            code: "not_found";
            /** @description Human-readable explanation of the failure. */
            message: string;
        };
        /**
         * @description A candidate booking window for an `EventType`, generated server-side
         *     on the 30-minute grid within business hours and the 14-day window.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Inclusive start of the slot (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Exclusive end of the slot (UTC); `start + durationMinutes`.
             */
            end: string;
        };
        /**
         * @description Returned when the requested slot overlaps an existing booking
         *     (the owner can only attend one call at a time).
         */
        SlotConflictError: {
            /**
             * @description Discriminating error code.
             * @enum {string}
             */
            code: "slot_conflict";
            /** @description Human-readable explanation of the failure. */
            message: string;
        };
        /**
         * @description Returned when the request payload fails validation (e.g. blank title,
         *     off-grid start time, past or out-of-window booking).
         */
        ValidationError: {
            /**
             * @description Discriminating error code.
             * @enum {string}
             */
            code: "validation_error";
            /** @description Human-readable explanation of the failure. */
            message: string;
            /** @description Optional list of field-level validation messages. */
            details?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: {
                /** @description Only include bookings starting at or after this instant (UTC). */
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /**
             * @description Returned when the request payload fails validation (e.g. blank title,
             *     off-grid start time, past or out-of-window booking).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Returned when a referenced resource (e.g. an `EventType`) does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /**
             * @description Returned when the requested slot overlaps an existing booking
             *     (the owner can only attend one call at a time).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotConflictError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /**
             * @description Returned when the request payload fails validation (e.g. blank title,
             *     off-grid start time, past or out-of-window booking).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_listSlots: {
        parameters: {
            query?: {
                /** @description Restrict slots to this single calendar day (owner-local). */
                date?: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Returned when a referenced resource (e.g. an `EventType`) does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
